- name: Deply mongo DB
  hosts: DB
  become: true
  gather_facts: true

  tasks:

  - name: Import MongoDB public GPG Key
    ansible.builtin.apt_key:
    url: https://pgp.mongodb.com/server-7.0.asc
    state: present

  # Adding MongoDB to the system's repository sources
  - name: Add MongoDB repository
    ansible.builtin.apt_repository:
      repo: 'deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse'
      state: present

  - name: install mongodb
    apt: pkg=mongodb-org state=latest update_cache=yes
    notify:
    - start mongodb

  # This task runs the equivalent of 'apt-get update' to refresh package lists
  # Similar to running 'sudo apt update' on Ubuntu/Debian
  - name: Update all packages
    ansible.builtin.apt:
      # 'update_cache: yes' tells Ansible to update the local package cache
      # This ensures you have the latest information about available packages
      update_cache: yes
  
  # This task upgrades all packages to their latest versions
  # Similar to running 'sudo apt-get dist-upgrade' on Ubuntu/Debian
  - name: Upgrade all packages
    ansible.builtin.apt:
      # 'upgrade: dist' performs a distribution upgrade (more comprehensive than 'yes')
      # Options are: yes, safe, full, dist (in increasing order of aggressiveness)
      upgrade: dist