---

# Name of the play
- name: Install nginx play
  # Where do you want to install or run this play
  hosts: web

  # Gather facts?
  gather_facts: true

  # Instructions - known as "tasks"
  tasks:
  
  # run apt update
  - name: Update all packages
    ansible.builtin.apt:
      update_cache: yes

  # run apt upgrade
  - name: Upgrade all packages
    ansible.builtin.apt:
      upgrade: dist
  
  # install and run nginx
  - name: Install and run nginx web server on target node
    # use package "nginx", "state=present" means package must be present and installed
    apt: pkg=nginx state=present